/*
・ iHorizon Discord Bot (https://gitlab.com/ihrz/ihrz)

・ Licensed under the Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)

	・   Under the following terms:

		・ Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

		・ NonCommercial — You may not use the material for commercial purposes.

		・ ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

		・ No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.


・ Mainly developed by Kisakay (https://gitlab.com/Kisakay)

・ Copyright © 2020-2025 iHorizon
*/

// Disclaimer: Most of these codes lines are generated by an LLM (Claude) model. The code are refactored and modified to fit the project's codebase.

import Jimp from 'jimp';

interface RGB {
	r: number;
	g: number;
	b: number;
}

interface HSL {
	h: number;  // Hue (0-360)
	s: number;  // Saturation (0-100)
	l: number;  // Lightness (0-100)
}

/**
 * Converts RGB to HSL
 */
function rgbToHsl(rgb: RGB): HSL {
	const r = rgb.r / 255;
	const g = rgb.g / 255;
	const b = rgb.b / 255;

	const max = Math.max(r, g, b);
	const min = Math.min(r, g, b);
	const diff = max - min;

	let h = 0;
	let s = 0;
	const l = (max + min) / 2;

	if (diff !== 0) {
		s = l > 0.5 ? diff / (2 - max - min) : diff / (max + min);

		switch (max) {
			case r:
				h = (g - b) / diff + (g < b ? 6 : 0);
				break;
			case g:
				h = (b - r) / diff + 2;
				break;
			case b:
				h = (r - g) / diff + 4;
				break;
		}
		h *= 60;
	}

	return {
		h,
		s: s * 100,
		l: l * 100
	};
}

/**
 * Converts RGB to Hex
 */
function rgbToHex(rgb: RGB): string {
	const toHex = (n: number): string => {
		const hex = Math.round(n).toString(16);
		return hex.length === 1 ? '0' + hex : hex;
	};
	return `#${toHex(rgb.r)}${toHex(rgb.g)}${toHex(rgb.b)}`;
}

/**
 * Calculates the "vibrancy" score of a color
 * based on saturation and lightness
 */
function getVibrancyScore(hsl: HSL): number {
	// Favors saturated colors with medium-high lightness
	const saturationWeight = 1.5;
	const lightnessWeight = 1.0;
	const optimalLightness = 60; // Prefers colors that are neither too dark nor too light

	const lightnessScore = 100 - Math.abs(hsl.l - optimalLightness);
	return (hsl.s * saturationWeight) + (lightnessScore * lightnessWeight);
}

/**
 * Extracts a vibrant and a dark dominant color from an image
 */
export default async function getVibrantAndDarkColors(input: string | Buffer): Promise<string> {
	try {
		// Handle different input types
		let image: Jimp;

		if (Buffer.isBuffer(input)) {
			image = await Jimp.read(input);
		} else if (typeof input === 'string' && (input.startsWith('http://') || input.startsWith('https://'))) {
			image = await Jimp.read(input);
		} else if (typeof input === 'string') {
			// Assume it's a file path or base64
			image = await Jimp.read(input);
		} else {
			throw new Error('Invalid input type. URL, file path or Buffer expected');
		}

		// Resize if necessary
		const maxDimension = 300;
		if (image.getWidth() > maxDimension || image.getHeight() > maxDimension) {
			image.scaleToFit(maxDimension, maxDimension);
		}

		// Color analysis
		const colorMap = new Map<string, { color: RGB; count: number }>();

		image.scan(0, 0, image.getWidth(), image.getHeight(), (x, y, idx) => {
			const r = image.bitmap.data[idx];
			const g = image.bitmap.data[idx + 1];
			const b = image.bitmap.data[idx + 2];

			// Color simplification
			const simplifiedR = Math.round(r / 10) * 10;
			const simplifiedG = Math.round(g / 10) * 10;
			const simplifiedB = Math.round(b / 10) * 10;

			const colorKey = `${simplifiedR},${simplifiedG},${simplifiedB}`;

			if (colorMap.has(colorKey)) {
				const colorCount = colorMap.get(colorKey)!;
				colorCount.count++;
			} else {
				colorMap.set(colorKey, {
					color: { r: simplifiedR, g: simplifiedG, b: simplifiedB },
					count: 1
				});
			}
		});

		const totalPixels = image.getWidth() * image.getHeight();

		// Filter and sort colors
		const colors = Array.from(colorMap.entries())
			.filter(([_, value]) => value.count > (totalPixels / 100)) // Ignore rare colors
			.map(([_, value]) => ({
				rgb: value.color,
				hsl: rgbToHsl(value.color),
				count: value.count
			}));

		// Separate colors into vibrant and dark
		const vibrantColors = colors
			.filter(color => color.hsl.l > 20 && color.hsl.s > 20)
			.sort((a, b) => getVibrancyScore(b.hsl) - getVibrancyScore(a.hsl));

		const darkColors = colors
			.filter(color => color.hsl.l < 40)
			.sort((a, b) => a.hsl.l - b.hsl.l);

		// Select the best colors
		const vibrantColor = vibrantColors[0]?.rgb || colors[0].rgb;
		const darkColor = darkColors[0]?.rgb || colors[colors.length - 1].rgb;

		return `${rgbToHex(vibrantColor)} ${rgbToHex(darkColor)}`;
	} catch (error) {
		console.error("Error analyzing image:", error);
		throw error;
	}
}