#!/usr/bin/env bun

/*
・ iHorizon Discord Bot (https://gitlab.com/ihrz/ihrz)

・ Licensed under the Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)

	・   Under the following terms:

		・ Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

		・ NonCommercial — You may not use the material for commercial purposes.

		・ ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

		・ No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.


・ Mainly developed by Kisakay (https://gitlab.com/Kisakay)

・ Copyright © 2020-2025 iHorizon
*/

// Code entierly generated by an AI model called Claude. Fuck don't care about "vibe coding" lol

// Types
interface VnStatData {
	vnstatversion: string;
	jsonversion: string;
	interfaces: Interface[];
}

interface Interface {
	name: string;
	traffic: {
		total: { rx: number; tx: number };
		fiveminute: TrafficEntry[];
		hour: TrafficEntry[];
		day: TrafficEntry[];
	};
}

interface TrafficEntry {
	timestamp: number;
	rx: number;
	tx: number;
}

interface Stats {
	avg: number;
	median: number;
	p95: number;
	p99: number;
	min: number;
	max: number;
	total: number;
}

// Utility functions
function formatBytes(bytes: number, decimals = 2): string {
	if (bytes === 0) return '0 B';
	const k = 1024;
	const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
	const i = Math.floor(Math.log(bytes) / Math.log(k));
	return parseFloat((bytes / Math.pow(k, i)).toFixed(decimals)) + ' ' + sizes[i];
}

function calculateStats(values: number[]): Stats {
	if (values.length === 0) {
		return { avg: 0, median: 0, p95: 0, p99: 0, min: 0, max: 0, total: 0 };
	}

	const sorted = [...values].sort((a, b) => a - b);
	const total = values.reduce((sum, val) => sum + val, 0);
	const avg = total / values.length;

	const getPercentile = (p: number) => {
		const index = Math.ceil((p / 100) * sorted.length) - 1;
		return sorted[index] || 0;
	};

	return {
		avg,
		median: getPercentile(50),
		p95: getPercentile(95),
		p99: getPercentile(99),
		min: sorted[0],
		max: sorted[sorted.length - 1],
		total
	};
}

function createBarChart(values: number[], labels: string[], width = 50, title = ''): string {
	const max = Math.max(...values);
	let chart = `\n${title}\n${'='.repeat(width + 20)}\n`;

	for (let i = 0; i < values.length; i++) {
		const barLength = Math.round((values[i] / max) * width);
		const bar = '█'.repeat(barLength);
		const padding = ' '.repeat(Math.max(0, 15 - labels[i].length));
		chart += `${labels[i]}${padding} ${bar} ${formatBytes(values[i])}\n`;
	}

	return chart;
}

function printStats(title: string, rxStats: Stats, txStats: Stats): void {
	console.log(`\n${'='.repeat(70)}`);
	console.log(`  ${title}`);
	console.log(`${'='.repeat(70)}`);
	console.log(`\n  Metric            │ Download (RX)        │ Upload (TX)`);
	console.log(`${'─'.repeat(70)}`);
	console.log(`  Total             │ ${formatBytes(rxStats.total).padEnd(20)} │ ${formatBytes(txStats.total)}`);
	console.log(`  Average           │ ${formatBytes(rxStats.avg).padEnd(20)} │ ${formatBytes(txStats.avg)}`);
	console.log(`  Median            │ ${formatBytes(rxStats.median).padEnd(20)} │ ${formatBytes(txStats.median)}`);
	console.log(`  95th Percentile   │ ${formatBytes(rxStats.p95).padEnd(20)} │ ${formatBytes(txStats.p95)}`);
	console.log(`  99th Percentile   │ ${formatBytes(rxStats.p99).padEnd(20)} │ ${formatBytes(txStats.p99)}`);
	console.log(`  Min               │ ${formatBytes(rxStats.min).padEnd(20)} │ ${formatBytes(txStats.min)}`);
	console.log(`  Max               │ ${formatBytes(rxStats.max).padEnd(20)} │ ${formatBytes(txStats.max)}`);
	console.log(`${'─'.repeat(70)}\n`);
}

function groupByWeek(dayData: TrafficEntry[]): { rx: number[]; tx: number[]; labels: string[] } {
	const weeks: Map<string, { rx: number; tx: number }> = new Map();

	dayData.forEach(entry => {
		const date = new Date(entry.timestamp * 1000);
		const weekStart = new Date(date);
		weekStart.setDate(date.getDate() - date.getDay());
		const weekKey = weekStart.toISOString().split('T')[0];

		if (!weeks.has(weekKey)) {
			weeks.set(weekKey, { rx: 0, tx: 0 });
		}
		const week = weeks.get(weekKey)!;
		week.rx += entry.rx;
		week.tx += entry.tx;
	});

	const sorted = Array.from(weeks.entries()).sort((a, b) => a[0].localeCompare(b[0]));
	return {
		rx: sorted.map(([_, v]) => v.rx),
		tx: sorted.map(([_, v]) => v.tx),
		labels: sorted.map(([k]) => k)
	};
}

function groupByMonth(dayData: TrafficEntry[]): { rx: number[]; tx: number[]; labels: string[] } {
	const months: Map<string, { rx: number; tx: number }> = new Map();

	dayData.forEach(entry => {
		const date = new Date(entry.timestamp * 1000);
		const monthKey = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;

		if (!months.has(monthKey)) {
			months.set(monthKey, { rx: 0, tx: 0 });
		}
		const month = months.get(monthKey)!;
		month.rx += entry.rx;
		month.tx += entry.tx;
	});

	const sorted = Array.from(months.entries()).sort((a, b) => a[0].localeCompare(b[0]));
	return {
		rx: sorted.map(([_, v]) => v.rx),
		tx: sorted.map(([_, v]) => v.tx),
		labels: sorted.map(([k]) => k)
	};
}

// Main
async function main() {
	console.log(`\n📊 Network Traffic Analyzer`);
	console.log(`Paste your vnStat JSON data and press Ctrl+D (or Ctrl+Z on Windows) when done:\n`);

	const decoder = new TextDecoder();
	const reader = Bun.stdin.stream().getReader();
	let jsonInput = '';

	try {
		while (true) {
			const { done, value } = await reader.read();
			if (done) break;
			jsonInput += decoder.decode(value, { stream: true });
		}
	} finally {
		reader.releaseLock();
	}

	let data: VnStatData;
	try {
		data = JSON.parse(jsonInput.trim());
	} catch (error) {
		console.error(`❌ Error parsing JSON: ${error}`);
		console.error(`Make sure you pasted valid JSON data.`);
		process.exit(1);
	}

	if (!data.interfaces || data.interfaces.length === 0) {
		console.error(`❌ No network interfaces found in the data.`);
		process.exit(1);
	}

	const iface = data.interfaces[0];
	console.log(`\n📊 Network Traffic Analysis for interface: ${iface.name}`);
	console.log(`vnStat version: ${data.vnstatversion}`);

	// Total statistics
	console.log(`\n${'='.repeat(70)}`);
	console.log(`  TOTAL TRAFFIC`);
	console.log(`${'='.repeat(70)}`);
	console.log(`  Download (RX): ${formatBytes(iface.traffic.total.rx)}`);
	console.log(`  Upload (TX):   ${formatBytes(iface.traffic.total.tx)}`);
	console.log(`  Total:         ${formatBytes(iface.traffic.total.rx + iface.traffic.total.tx)}`);

	// Daily statistics
	const dayRx = iface.traffic.day.map(d => d.rx);
	const dayTx = iface.traffic.day.map(d => d.tx);
	printStats('DAILY STATISTICS', calculateStats(dayRx), calculateStats(dayTx));

	// Hourly statistics
	const hourRx = iface.traffic.hour.map(h => h.rx);
	const hourTx = iface.traffic.hour.map(h => h.tx);
	printStats('HOURLY STATISTICS', calculateStats(hourRx), calculateStats(hourTx));

	// Weekly statistics
	const weekData = groupByWeek(iface.traffic.day);
	printStats('WEEKLY STATISTICS', calculateStats(weekData.rx), calculateStats(weekData.tx));

	// Monthly statistics
	const monthData = groupByMonth(iface.traffic.day);
	printStats('MONTHLY STATISTICS', calculateStats(monthData.rx), calculateStats(monthData.tx));

	// Charts
	console.log(createBarChart(
		monthData.rx.slice(-6),
		monthData.labels.slice(-6),
		60,
		'📈 DOWNLOAD (RX) - LAST 6 MONTHS'
	));

	console.log(createBarChart(
		monthData.tx.slice(-6),
		monthData.labels.slice(-6),
		60,
		'📤 UPLOAD (TX) - LAST 6 MONTHS'
	));

	// Top 10 days with highest traffic
	const topDays = iface.traffic.day
		.map((d, i) => ({
			date: new Date(d.timestamp * 1000).toISOString().split('T')[0],
			rx: d.rx,
			tx: d.tx,
			total: d.rx + d.tx
		}))
		.sort((a, b) => b.total - a.total)
		.slice(0, 10);

	console.log(`\n${'='.repeat(70)}`);
	console.log(`  TOP 10 DAYS - TOTAL TRAFFIC`);
	console.log(`${'='.repeat(70)}`);
	topDays.forEach((day, i) => {
		console.log(`  ${i + 1}. ${day.date}  │  ${formatBytes(day.total).padEnd(15)} (↓${formatBytes(day.rx)} ↑${formatBytes(day.tx)})`);
	});
	console.log();
}

main().catch(console.error);